version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
      - run: npm run stylelint
      - run: npm run test:jsdom
  publish-storybook:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run: npx storybook-to-ghpages
    requires:
      - test
    filters:
      branches:
        only:
          - master